[package]
name = "cccut"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cccut"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
